export const pdfEditorManifest = {
  slug: 'pdf-editor',
  title: 'PDF Editor',
  short_description: 'Edit PDF text, add digital signatures, redact sensitive data, reorder, rotate, and organize pages 100% locally in your browser.',
  shortDescription: 'Edit PDF text, add digital signatures, redact sensitive data, reorder, rotate, and organize pages 100% locally in your browser.',
  description: 'Free online PDF Editor with zero server uploads. Add text, draw or upload e-signatures, blackout private data, highlight sections, rotate, delete, duplicate, and reorder pages with instant high-quality export.',
  category: 'Document & PDF',
  icon_name: 'PenTool',
  iconName: 'PenTool',
  badge: '100% In-Browser Privacy',
  targetUrl: '#/tool/pdf-editor',
  features: [
    'Add text, notes, and callouts with custom fonts, colors, and sizes',
    'Sign documents with mouse, touchscreen, or uploaded PNG signatures',
    'Blackout and whiteout sensitive data (SSN, credit cards, confidential text)',
    'Fluorescent text highlighter, shapes, and bounding boxes',
    'Reorder, rotate, delete, duplicate, and add blank PDF pages',
    '1-click stamp overlays (APPROVED, CONFIDENTIAL, DRAFT, URGENT, FINAL)',
    'Automated "Page X of Y" page numbering',
    '100% Client-Side – zero files uploaded to servers (GDPR & HIPAA safe)'
  ],
  keywords: [
    'pdf editor',
    'free pdf editor online',
    'edit pdf without adobe acrobat',
    'add signature to pdf free',
    'sign pdf online',
    'redact pdf',
    'blackout pdf online',
    'rotate pdf pages',
    'reorder pdf pages',
    'delete pages from pdf',
    'organize pdf pages',
    'fill pdf forms free',
    'highlight pdf online',
    'client side pdf editor',
    'secure pdf editor hipaa gdpr',
    'sejda alternative free',
    'smallpdf alternative free',
    'add text to pdf free',
    'pdf stamp maker online',
    'no watermark pdf editor'
  ],
  seo_title: 'Free Online PDF Editor (2026) – Edit Text, Add Signature, Redact & Organize Pages | Cerilas Tools',
  seo_description: 'Edit PDF documents online for free with 100% client-side privacy. Add text, draw digital signatures, redact sensitive info, rotate, reorder, and delete pages. No file uploads, no signup, no watermark.',
  seo: {
    title: 'Free Online PDF Editor (2026) – Edit Text, Add Signature, Redact & Organize Pages | Cerilas Tools',
    description: 'Edit PDF documents online for free with 100% client-side privacy. Add text, draw digital signatures, redact sensitive info, rotate, reorder, and delete pages. No file uploads, no signup, no watermark.',
    keywords: 'pdf editor, free pdf editor online, edit pdf without adobe acrobat, add signature to pdf free, sign pdf online, redact pdf, blackout pdf online, rotate pdf pages, reorder pdf pages, delete pages from pdf, organize pdf pages, fill pdf forms free, highlight pdf online, client side pdf editor, secure pdf editor hipaa gdpr, sejda alternative free, smallpdf alternative free, add text to pdf free, pdf stamp maker online, no watermark pdf editor',
    ogImage: 'https://tools.cerilas.com/og-image.svg',
    ogImageAlt: 'Cerilas Free Online PDF Editor',
    breadcrumbsName: 'PDF Editor'
  }
};
