import { useState, useEffect } from 'react';
import { 
  Binary, 
  Layers, 
  Coins, 
  ShieldCheck, 
  ChevronDown, 
  Sparkles, 
  FileText, 
  ArrowUpRight,
  Cpu,
  Globe,
  Gauge,
  Zap,
  Tag,
  CheckCircle2
} from 'lucide-react';
import './TokenCounterSeo.css';

const FAQ_ITEMS = [
  {
    q: 'What is an LLM token and how is it calculated in 2026 models like GPT-6 Astra and Gemini 3.8?',
    a: 'In Large Language Models (LLMs), a token is the fundamental atomic unit of text and code processed by transformer neural networks. Tokens can be whole words, character fragments, syllables, or punctuation symbols. For standard English prose, 1 token roughly corresponds to 4 characters or ~0.75 words. Frontier 2026 models like OpenAI GPT-6 Astra and Google Gemini 3.8 utilize advanced multi-byte Byte-Pair Encoding (BPE) and SentencePiece vocabularies with over 200,000 unique token embeddings, optimizing multilingual compression and code syntax parsing.'
  },
  {
    q: 'How does GPT-6 Astra\'s 1.05M context window compare to Gemini 3.8 Flash and Claude 3.7 Sonnet?',
    a: 'GPT-6 Astra supports an expansive 1,050,000 (1.05M) token input context with up to 128,000 output tokens for complex agentic computer control and software development workflows. Gemini 3.8 Flash features a 1,000,000 (1M) token context with tunable reasoning thinking tokens, while Claude 3.7 Sonnet provides 200,000 tokens with extended hybrid reasoning budgets. Our Universal Token Counter calculates exact token consumption and remaining headroom across all three architectures simultaneously.'
  },
  {
    q: 'Why do languages like Turkish, German, Arabic, and Japanese consume more tokens than English?',
    a: 'Because the vast majority of training datasets for foundational LLMs are English-heavy, tokenizers allocate individual token IDs to common English words and roots. In agglutinative languages such as Turkish, affixes, suffixes, and compound word structures are split into 2 to 5 sub-word tokens per word. While modern o200k vocabularies improved Turkish compression by ~28%, non-English text still experiences 1.3x to 2.2x token inflation compared to English prose.'
  },
  {
    q: 'Are my uploaded documents (PDF, source code, confidential prompts) sent to any server?',
    a: 'Never. Cerilas Universal Token Counter operates 100% client-side directly within your web browser using WebAssembly and pure JavaScript. Document text extraction from PDFs and tokenization are computed entirely in local browser memory. Zero prompts, files, or sensitive payloads are uploaded or logged to any remote server.'
  },
  {
    q: 'How does prompt token size impact LLM API latency, TTFT, and generation cost?',
    a: 'Longer prompts directly increase Time to First Token (TTFT) and increase self-attention matrix operations quadratically or linearly depending on attention optimizations (FlashAttention / KV Cache). Furthermore, large prompts that fill 70%+ of the model\'s context window suffer from retrieval degradation ("lost in the middle"). Keeping your prompt compact through 1-click token reduction saves 15-40% on API billing and dramatically reduces inference latency.'
  },
  {
    q: 'What is the difference between o200k_base, cl100k_base, and Gemini SentencePiece tokenizers?',
    a: 'cl100k_base was the default vocabulary for GPT-4 and GPT-3.5 Turbo with a 100k-token dictionary. o200k_base (used in GPT-6 Astra, GPT-4o, o1, and o3-mini) doubled the vocabulary to 200,000 tokens, significantly decreasing token count for non-English languages, emoji sequences, and programming languages. Google Gemini uses a customized SentencePiece tokenizer specifically trained on multilingual and multimodal text representations.'
  },
  {
    q: 'How can developers optimize prompts to shave 20-40% off their LLM API budget?',
    a: '1) Strip unnecessary whitespace and redundant newlines. 2) Remove developer comments from source code files before feeding them into prompt context. 3) Strip boilerplate HTML/XML markup and convert web data to clean Markdown using our HTML-to-LLM converter. 4) Leverage prompt caching for static system messages and reference schemas.'
  },
  {
    q: 'Can I calculate token counts for PDF documents and source code repositories for RAG?',
    a: 'Yes. You can drag and drop PDF files (manuals, research papers, legal documents) or source code files (.py, .js, .ts, .go, .rs, .json, .csv). Our engine extracts text on the fly without server uploads and outputs real-time token statistics, character counts, and model cost projections for optimal RAG chunk sizing.'
  },
  {
    q: 'What are "thinking tokens" in Claude 3.7 Sonnet and Gemini 3.8 Flash?',
    a: 'Thinking tokens represent the internal chain-of-thought tokens generated by reasoning models prior to producing the final user-facing response. While users typically view the final answer, reasoning models bill for thinking tokens at output token rates. Our calculator provides baseline cost models for both standard prompts and extended reasoning workloads.'
  },
  {
    q: 'How accurate is this online token counter compared to official Python SDKs?',
    a: 'Universal Token Counter utilizes official WebAssembly and compiled JavaScript implementations of Tiktoken (o200k and cl100k BPE byte dictionaries). For GPT-6 Astra, GPT-4o, o1, and GPT-4, the token counts are 100% bit-exact with the official OpenAI tiktoken Python library.'
  }
];

const SEMANTIC_KEYWORDS = [
  'GPT-6 Astra Token Counter',
  'Gemini 3.8 Flash Token Calculator',
  'Claude 3.7 Sonnet Tokenizer',
  'OpenAI o200k_base Tiktoken Online',
  'DeepSeek-V3 Token Cost Calculator',
  'Free PDF Token Counter',
  'Token to Word Ratio Converter',
  'Client-Side Private Tokenizer',
  'LLM Context Window Gauge',
  'AI Prompt Cost Estimator (2026)',
  'Llama 3.3 70B Token Counter',
  'Turkish Token Inflation Analyzer'
];

const RELATED_TOOLS = [
  { name: 'HTML to LLM Markdown', desc: 'Convert web pages to token-efficient clean Markdown for LLMs.', href: '#/tool/html-to-llm-markdown' },
  { name: 'PDF → RAG Cleaner', desc: 'Extract and clean messy PDFs into structured vector chunks.', href: '#/tool/pdf-rag-cleaner' },
  { name: 'LLMs.txt Tools', desc: 'Generate and validate /llms.txt site guides for AI crawlers.', href: '#/tool/llms-txt' },
  { name: 'AI Link Hallucination Checker', desc: 'Audit AI generated drafts for broken or hallucinated URLs.', href: '#/tool/ai-link-hallucination-checker' },
  { name: 'AI Crawler Checker', desc: 'Verify if GPTBot, ClaudeBot, and Perplexity can access your site.', href: '#/tool/ai-crawler-checker' },
  { name: 'JSON Beautifier', desc: 'Format and inspect JSON payloads for AI API endpoints.', href: '#/tool/json-beautifier' }
];

export default function TokenCounterSeo() {
  const [openFaq, setOpenFaq] = useState(null);

  useEffect(() => {
    // 1. FAQ Schema
    const faqStructuredData = {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      'mainEntity': FAQ_ITEMS.map((item) => ({
        '@type': 'Question',
        'name': item.q,
        'acceptedAnswer': {
          '@type': 'Answer',
          'text': item.a
        }
      }))
    };

    // 2. WebApplication Schema
    const appStructuredData = {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      'name': 'Universal Token Counter & LLM Cost Calculator',
      'operatingSystem': 'All',
      'applicationCategory': 'DeveloperApplication',
      'url': 'https://tools.cerilas.com/#/tool/token-counter-universal',
      'offers': {
        '@type': 'Offer',
        'price': '0',
        'priceCurrency': 'USD'
      },
      'description': 'Free client-side token counter and API cost calculator for GPT-6 Astra, Gemini 3.8 Flash, Claude 3.7 Sonnet, DeepSeek-V3, and Llama 3.3. Interactive color visualizer with zero server uploads.'
    };

    let scriptFaq = document.getElementById('token-counter-faq-jsonld');
    if (!scriptFaq) {
      scriptFaq = document.createElement('script');
      scriptFaq.id = 'token-counter-faq-jsonld';
      scriptFaq.type = 'application/ld+json';
      document.head.appendChild(scriptFaq);
    }
    scriptFaq.textContent = JSON.stringify(faqStructuredData);

    let scriptApp = document.getElementById('token-counter-app-jsonld');
    if (!scriptApp) {
      scriptApp = document.createElement('script');
      scriptApp.id = 'token-counter-app-jsonld';
      scriptApp.type = 'application/ld+json';
      document.head.appendChild(scriptApp);
    }
    scriptApp.textContent = JSON.stringify(appStructuredData);

    return () => {
      const elFaq = document.getElementById('token-counter-faq-jsonld');
      if (elFaq) elFaq.remove();
      const elApp = document.getElementById('token-counter-app-jsonld');
      if (elApp) elApp.remove();
    };
  }, []);

  return (
    <div className="tc-seo-container">
      {/* Intro Header */}
      <div className="tc-seo-header">
        <h2 className="tc-seo-title">Universal Multi-Model Token Architecture & Cost Guide (2026)</h2>
        <p className="tc-seo-intro">
          Designing production LLM applications, RAG pipelines, and agentic workflows requires precise awareness of
          tokenizer vocabularies, context window limitations, and token economics. Cerilas Universal Token Counter
          delivers bit-exact token calculations, interactive token boundary visualization, and 2026 API cost analytics
          with 100% in-browser client-side privacy.
        </p>
      </div>

      {/* Feature Pillar Cards */}
      <div className="tc-seo-grid">
        <div className="tc-seo-card">
          <div className="tc-seo-card-icon">
            <Binary size={20} />
          </div>
          <h3 className="tc-seo-card-title">Bit-Exact Token Boundaries</h3>
          <p className="tc-seo-card-desc">
            Visualize how tokenizers segment sentences, syntax, punctuation, and whitespace into token IDs. Inspect
            exact token boundaries with color-coded chips and zero React re-render lag during text selection.
          </p>
        </div>

        <div className="tc-seo-card">
          <div className="tc-seo-card-icon">
            <Coins size={20} />
          </div>
          <h3 className="tc-seo-card-title">2026 Frontier Cost Audit</h3>
          <p className="tc-seo-card-desc">
            Calculate instant prompt costs and 1k-completion estimates across 20+ models including GPT-6 Astra,
            Gemini 3.8 Flash, Claude 3.7 Sonnet, DeepSeek-V3, and Grok 3.
          </p>
        </div>

        <div className="tc-seo-card">
          <div className="tc-seo-card-icon">
            <ShieldCheck size={20} />
          </div>
          <h3 className="tc-seo-card-title">100% Client-Side Privacy</h3>
          <p className="tc-seo-card-desc">
            All text and PDF document parsing runs inside your web browser via WebAssembly. Confidential corporate
            prompts, IP-protected codebases, and customer datasets never leave your computer.
          </p>
        </div>
      </div>

      {/* Model Architecture Comparison Table */}
      <div className="tc-seo-table-section">
        <h3 className="tc-seo-section-heading">
          <Cpu size={18} style={{ color: '#6366f1' }} />
          <span>2026 Frontier LLM Tokenizer & Pricing Specifications</span>
        </h3>
        <p className="tc-seo-section-subtitle">
          Overview of official context limits, tokenizer families, and current API pricing per 1 million tokens.
        </p>
        <div className="tc-seo-table-wrap">
          <table className="tc-seo-specs-table">
            <thead>
              <tr>
                <th>Model</th>
                <th>Provider</th>
                <th>Tokenizer</th>
                <th>Context Window</th>
                <th>Max Output</th>
                <th>Input / 1M</th>
                <th>Output / 1M</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>GPT-6 Astra</strong></td>
                <td>OpenAI</td>
                <td><code>o200k_base</code></td>
                <td>1,050,000 (1.05M)</td>
                <td>128,000</td>
                <td>$10.00</td>
                <td>$50.00</td>
              </tr>
              <tr>
                <td><strong>Gemini 3.8 Flash</strong></td>
                <td>Google</td>
                <td><code>SentencePiece</code></td>
                <td>1,000,000 (1M)</td>
                <td>64,000</td>
                <td>$0.75</td>
                <td>$3.75</td>
              </tr>
              <tr>
                <td><strong>Claude 3.7 Sonnet</strong></td>
                <td>Anthropic</td>
                <td><code>Claude BPE</code></td>
                <td>200,000</td>
                <td>64,000</td>
                <td>$3.00</td>
                <td>$15.00</td>
              </tr>
              <tr>
                <td><strong>DeepSeek-V3</strong></td>
                <td>DeepSeek</td>
                <td><code>DeepSeek BPE</code></td>
                <td>64,000</td>
                <td>8,000</td>
                <td>$0.28</td>
                <td>$2.19</td>
              </tr>
              <tr>
                <td><strong>Gemini 3.1 Pro</strong></td>
                <td>Google</td>
                <td><code>SentencePiece</code></td>
                <td>1,000,000 (1M)</td>
                <td>32,768</td>
                <td>$2.00</td>
                <td>$12.00</td>
              </tr>
              <tr>
                <td><strong>Grok 3</strong></td>
                <td>xAI</td>
                <td><code>o200k</code></td>
                <td>1,000,000 (1M)</td>
                <td>64,000</td>
                <td>$3.00</td>
                <td>$15.00</td>
              </tr>
              <tr>
                <td><strong>Llama 3.3 70B</strong></td>
                <td>Meta</td>
                <td><code>tiktoken 128k</code></td>
                <td>128,000</td>
                <td>8,192</td>
                <td>$0.59</td>
                <td>$0.79</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Language Token Inflation Guide */}
      <div className="tc-seo-table-section">
        <h3 className="tc-seo-section-heading">
          <Globe size={18} style={{ color: '#06b6d4' }} />
          <span>Multilingual Token Inflation & Word-to-Token Ratios</span>
        </h3>
        <p className="tc-seo-section-subtitle">
          Agglutinative and non-Latin languages require multiple sub-word tokens per word, directly scaling inference costs.
        </p>
        <div className="tc-seo-table-wrap">
          <table className="tc-seo-specs-table">
            <thead>
              <tr>
                <th>Language</th>
                <th>Avg Characters / Token</th>
                <th>Token-to-Word Ratio</th>
                <th>Token Inflation Index</th>
                <th>o200k Compression Status</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>English</strong></td>
                <td>4.2 chars</td>
                <td>~1.3 tokens/word</td>
                <td>1.0x (Baseline)</td>
                <td>Optimal</td>
              </tr>
              <tr>
                <td><strong>Turkish</strong></td>
                <td>2.6 chars</td>
                <td>~2.4 tokens/word</td>
                <td>1.85x inflation</td>
                <td>+28% more efficient than cl100k</td>
              </tr>
              <tr>
                <td><strong>German</strong></td>
                <td>3.1 chars</td>
                <td>~1.8 tokens/word</td>
                <td>1.38x inflation</td>
                <td>+22% more efficient</td>
              </tr>
              <tr>
                <td><strong>Spanish / French</strong></td>
                <td>3.5 chars</td>
                <td>~1.6 tokens/word</td>
                <td>1.23x inflation</td>
                <td>High compression</td>
              </tr>
              <tr>
                <td><strong>Arabic</strong></td>
                <td>1.9 chars</td>
                <td>~2.8 tokens/word</td>
                <td>2.15x inflation</td>
                <td>+35% more efficient</td>
              </tr>
              <tr>
                <td><strong>Japanese / Chinese</strong></td>
                <td>1.5 chars</td>
                <td>~2.2 tokens/word</td>
                <td>1.70x inflation</td>
                <td>Dedicated multi-byte token maps</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Semantic Search Keywords Cloud */}
      <div className="tc-seo-keywords-block">
        <div className="tc-seo-keywords-title">
          <Tag size={15} />
          <span>Popular Search Queries & Topics</span>
        </div>
        <div className="tc-seo-pills-wrap">
          {SEMANTIC_KEYWORDS.map((kw, i) => (
            <span key={i} className="tc-keyword-tag">
              <CheckCircle2 size={12} className="tc-tag-check" />
              {kw}
            </span>
          ))}
        </div>
      </div>

      {/* FAQ Section */}
      <div className="tc-faq-section">
        <h2 className="tc-faq-title">Frequently Asked Questions</h2>
        <div className="tc-faq-list">
          {FAQ_ITEMS.map((item, idx) => {
            const isOpen = openFaq === idx;
            return (
              <div key={idx} className="tc-faq-item">
                <button
                  type="button"
                  className="tc-faq-question"
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  aria-expanded={isOpen}
                >
                  <span>{item.q}</span>
                  <ChevronDown size={18} className={`tc-faq-icon ${isOpen ? 'open' : ''}`} />
                </button>
                {isOpen && (
                  <div className="tc-faq-answer">
                    <p>{item.a}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Related Tools */}
      <div className="tc-related-section">
        <h3 className="tc-related-title">Explore Related AI & Developer Tools</h3>
        <div className="tc-related-grid">
          {RELATED_TOOLS.map((tool, idx) => (
            <a key={idx} href={tool.href} className="tc-related-card">
              <div>
                <div className="tc-related-name">
                  <span>{tool.name}</span>
                  <ArrowUpRight size={14} />
                </div>
                <p className="tc-related-desc">{tool.desc}</p>
              </div>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}

